# 公共配置文件
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  redis:
    port: 6379
    host: localhost
    database: 1
    password: 123321
  application:
    name: user-center-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yupi
    username: root
    password: Lovelzx629916.
  # session 失效时间
  session:
    timeout: 86400
    store-type: redis
  port: 8080
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  profiles:
    active: dev

server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可 以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)